---
area/ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"
area/nix:
  - changed-files:
      - any-glob-to-any-file: "**/*.nix"
  - changed-files:
      - any-glob-to-any-file: "flake.lock"
