#!/usr/bin/env bash
#MISE description="Build darwin configuration for the current host"

set -euo pipefail

host="${HOST_ALIAS:-$(hostname -s)}"

echo "Building configuration for '$host' ..."
if [ "$host" = "cmb" ]; then
	nh darwin build . -n -- --override-input corpo path:../dots.corpo
else
	nh darwin build . -n
fi
