#!/usr/bin/env bash
#MISE description="Show diff between current and new configuration"

set -euo pipefail

host="${HOST_ALIAS:-$(hostname -s)}"

echo "Building for diff '$host' ..."
if [ "$host" = "cmb" ]; then
	nh darwin build . -n -d always --override-input corpo path:../dots.corpo
else
	nh darwin build . -n -d always
fi
