#!/usr/bin/env bash
#MISE description="Build and activate darwin configuration for the current host"

set -euo pipefail

host="${HOST_ALIAS:-$(hostname -s)}"

echo "Building configuration for '$host' ..."
if [ "$host" = "cmb" ]; then
	nh darwin switch . -- --override-input corpo path:../dots.corpo
else
	nh darwin switch .
fi
