---
keys:
  - &host_asc age15y7e536y0duw05v30u8m27rjq74kn3y7sszywrxu2kpzxdcx8f6qyqymfu
  - &host_ley age1z4z6atdekrwtcf5ntahgadnkdwz9cmc2mtj8c8g7l5vznwp3fytsd5e9c7
  - &host_pmb age1f6tcx8pdsqc7eyedgj9vet4ga94enx6v349y73kmg0xg8uyek5ysfpmm2c
  - &user_c4300n age1qr30xfa47s84mcdcsp0h69x7ryflckmc20reyezc9wfysleeydvqc2v2y3
  - &user_trash-panda-v91-beta age1k2f79x0m9lcu7x2vyemph9m5rrgezfy3kgl0gz7zjwuuwrhnfy0slpn0d6
creation_rules:
  - path_regex: .*\.sops\.ya?ml$
    key_groups:
      - age:
          - *host_asc
          - *host_ley
          - *host_pmb
          - *user_c4300n
          - *user_trash-panda-v91-beta
